### PR TITLE
Fix/adjust cmake files to use libavxpinpad

### PR DESCRIPTION
**Pull request by mgsasaki**
Modification done on the projects cmake files to use the latests changes to avxpinpad library
https://trello.com/c/eWHyy0pw

### CODE REVIEW

**Comment by mgsasaki** [comment]
It also includes the modifications done to port the demoPinpad application from the developing enviroment to the SDK

**Comment by edhana** [comment]
@mgsasaki I've restored the branch because, with a clean environment there is a library missing. The library is libpinpad_hal.a, Could you load this library and re-send the pull request?

**Comment by mgsasaki** [comment]
@edhana this library is compiled when you copile the demoPinpad project
maybe we could move this library to another project on the SDK

**Comment by edhana** [comment]
Nice, the problem occurs when I try to build the hole SDK libraries and examples, so maybe something is happening out of the correct order.

**Comment by edhana** [comment]
It's a good idea to move this library to other SDK project

**Comment by mgsasaki** [comment]
I'll do that, and also add the depency.

**Pull request merged**
